/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn _plat__RunCommand(
        requestSize: u32,
        request: *mut crate::cty::c_uchar,
        responseSize: *mut u32,
        response: *mut *mut crate::cty::c_uchar,
    );
}

extern "C" {
    pub fn _plat__TPM_Terminate() -> crate::cty::c_int;
}

extern "C" {
    pub fn _plat__TPM_Initialize(
        firstTime: crate::cty::c_int,
        platParameter: *mut crate::cty::c_void,
    ) -> crate::cty::c_int;
}

extern "C" {
    pub fn _plat__NvMemoryRead(
        startOffset: crate::cty::c_uint,
        size: crate::cty::c_uint,
        data: *mut crate::cty::c_void,
    );
}

extern "C" {
    pub fn _TPM_Hash_Start();
}

extern "C" {
    pub fn _TPM_Hash_Data(dataSize: u32, data: *mut crate::cty::c_uchar);
}

extern "C" {
    pub fn _TPM_Hash_End();
}
