permissions:
  contents: read

on:
    push:
      paths-ignore:
        - "**.md"
    pull_request:
      paths-ignore:
        - "**.md"
  
name: Build binary
  
env:
  AS: nasm
  RUST_TOOLCHAIN: nightly-2023-12-31
  TOOLCHAIN_PROFILE: minimal
  
jobs:
    system_compile:
      name: Compile the vtpmtd.bin file
      runs-on: ubuntu-20.04
      timeout-minutes: 30
  
      steps:
        - name: Harden Runner
          uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
          with:
            egress-policy: audit

        - name: Checkout vTPM-Td Sources
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Initialize and update submodules
          run: |
            git config --global http.postBuffer 524288000
            git config --global http.sslVerify "false"
            git submodule update --init --recursive --depth 1
        
        - name: Install LLVM and Clang
          uses: KyleMayes/install-llvm-action@e0a8dc9cb8a22e8a7696e8a91a4e9581bec13181 # v2.0.5
          with:
            version: "10.0"
            directory: ${{ runner.temp }}/llvm

        - name: install NASM
          uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2
        
        - name: Install tools for tpm-ref build
          run: |
            sudo apt-get autoclean
            sudo apt-get update
            sudo apt-get upgrade
            sudo apt-get install autoconf-archive pkg-config build-essential automake gcc libssl-dev ocaml ocamlbuild autoconf libtool wget python-is-python3 cmake perl gcc-multilib
 
        - name: Install toolchain
          uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
          with:
            profile: ${{ env.TOOLCHAIN_PROFILE }}
            toolchain: ${{ env.RUST_TOOLCHAIN }}
            override: true
            components: rust-src
  
        - name: Run cargo install cargo-xbuild
          uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
          with:
            command: install
            args: cargo-xbuild
  
        - name: Preparation Work
          run: bash sh_script/pre-build.sh
  
        - name: Run cargo check
          run: |
            cargo check
  
        - name: Build vTPM-TD
          env:
            CC: clang
            AR: llvm-ar
          run: bash sh_script/build.sh